name: ouroboros
services:
  redis:
    type: redis
    app_mount: false
  appserver:
    type: node:16
    overrides:
      environment:
        TOKEN: '**OVERRIDE THIS LOCALLY**'
        REDIS_TLS_URL: 'redis://redis'
    build:
      - npm install
tooling:
  node:
    service: appserver
  npm:
    service: appserver
